### ISSUE TITLE
Odoo 11, Event Calendar and List Snippet and Iframe fail dependency loading

### ISSUE THREAD

**Issue by devingfx** [OCA/event#126]
After install on odoo 11, there is a js dependency fail message on dep
`web_editor.snipets.animation` 

Making the js part of this module not loading at all and have infinite spinners on website snippet.

The loading takes place in `website_event_snippet_calendar/static/src/js/animation.js`

II replaced the require with:
```javascript
 var animation = require("website.content.snippets.animation");
```
And it corrected the problem...

**Comment by pedrobaeza** [comment]
Module is not migrated to v11, so it's normal that it fails. Please propose a migration PR.
