### ISSUE TITLE
[12.0][ADD] website_event_group or website_slides_event New module

### ISSUE THREAD

**Issue by emagdalenaC2i** [OCA/event#141]
I would like to have some feedback before starting with this module that I will try to develop soon.

Currently website_slides allows to sort presentations in channels and restrict the access to a channel to one or more user groups.

![image](https://user-images.githubusercontent.com/24428859/55696148-f70b9a80-59bb-11e9-8217-d4f5cde53e01.png)

My intention is to allow access to a website_slides channel only to confirmed attendees of an event. Probably there are several ways to do that, and that's why I'd like to have your feedback.

![image](https://user-images.githubusercontent.com/24428859/55696940-836b8c80-59bf-11e9-87f3-df6149757bbd.png)

My idea is the following:
1-This module will depend on #135 website_event_require_login, so that attendees to the event already have a registered user
2-This module will add an option to create a group with all its confirmed attendees
3-That group could be used directly to restrict access to the desired presentation channels

What do you think? Any recommendation?

@chienandalu, @pedrobaeza, @Yajo and @rafaelbn I don't know if you are going to migrate website_event_require_login to v11 and v12, but I can try it

**Comment by pedrobaeza** [comment]
There are no plans for now to migrate it.

About the new feature, instead of creating fake security groups, I would go for expanding the security check (there are ORM methods for that), for allowing read access in case the partner of the current user are register in the event.

**Comment by emagdalenaC2i** [comment]
Could you give me an example?

**Comment by pedrobaeza** [comment]
https://github.com/odoo/odoo/blob/3017aecd095c6760997e3e6f77300589d4e68e2a/addons/mail/models/mail_message.py#L675
