### ISSUE TITLE
[12.0] Event Session registration for websites

### ISSUE THREAD

**Issue by llacroix** [OCA/event#180]
Would you be interested to merge a module that enable event_session to be selected on the website registration page?

We made a module to add this functionality. I wouldn't mind have it merged here but I'd like to know how would it be prefered as a website_event_session module or there's a module it could be integrated directly into?

**Comment by chienandalu** [comment]
I think a website_event_session module would be ok. Thanks :)

**Comment by llacroix** [comment]
https://github.com/OCA/event/pull/181
