### ISSUE TITLE
Clarification about partner_event search feature

### ISSUE THREAD

**Issue by yaazkal** [OCA/event#199]
Hi, I'm trying to use the `partner_event` module (Odoo 13).

I can read that the module says: "Search partners by their event attendees". As I user I'm expecting to search for partners that has attended to event "showroom 2020" for example. Does it mean it has that feature? or what kind of search is that the user is able to do?

Thanks for the clarification.

**Comment by pedrobaeza** [comment]
This module links partners with attendees, so it allows at partner level to show the events that have linked registrations.

**Comment by yaazkal** [comment]
Thanks for the clarification.
