### ISSUE TITLE
[ENH] partner_event: offering to develop creation of partner from backend sales

### ISSUE THREAD

**Issue by kwoychesko** [OCA/event#310]
Partner_event is a great module and I'm grateful to the community that it exists. I have an ENH that I'm willing to develop but wanted some input from the community.

Currently, if you sell tickets from the Sales module, you receive the pop-up requesting the details of the Attendees, but these Attendees are not created as Partners (attendees from the Website are created, of course).

I'm offering to develop the code necessary to create Partners from Attendees created via the Sales module, but:

1. wanted to be sure there was interest in this from others for this feature, and
2. wanted to make sure there wasn't anything I was missing (e.g. a good reason *why* partners aren't created from backend sales, or maybe why my suggested ENH should be a separate module, etc.)

Thank you for your input!

**Comment by chienandalu** [comment]
Hi @kwoychesko I think your proposal was addressed here: https://github.com/OCA/event/pull/342
