### ISSUE TITLE
Branch 14 ... 14.0/event_session/models/event_session.py refering to Branch 13 Data  (Line 16-17)

### ISSUE THREAD

**Issue by l-arnold** [OCA/event#330]
(https://github.com/OCA/event/blob/14.0/event_session/models/event_session.py)

Line 16-17 is referring to Branch 13 Data.  Previous Branches have syncronized Data references 
`    https://github.com/odoo/odoo/blob/13.0/odoo/addons/base/models
    /ir_qweb_fields.py#L238`

## Module
event_session

## Describe the bug
I have no idea if the data model is different but seems it should refer to the same branch

## To Reproduce
14

go to:
event_session/models/event_session.py

**Expected behavior**

Probably need it to read:
``    https://github.com/odoo/odoo/blob/13.0/odoo/addons/base/models
    /ir_qweb_fields.py#L238``
    
but I don't now about the #L238 part

**Additional context**
This started because I need Sessions to show up on the Website but am not getting that even with event_sale_sessions also installed.  Ran into this and thought I would comment.

**Comment by pedrobaeza** [comment]
Please propose a PR putting and absolute reference (permalink).
