### ISSUE TITLE
Event Sale Reservation to Branch 14

### ISSUE THREAD

**Issue by l-arnold** [OCA/event#331]
**Is your feature request related to a problem?**
I see Event Sale Reservation in Branch 13 and Branch 15, but not Branch 14.
https://github.com/OCA/event/tree/13.0/event_sale_reservation
https://github.com/OCA/event/tree/15.0/event_sale_reservation
(get a 404 if you put 14.0 in there)

I also see that Vertel has the module listed in their Branch 14
https://github.com/vertelab/odoo-event/tree/14.0/event_sale_reservation

**Describe the solution you'd like**
 so hoping we can keep things as OCA rather than mixing names and the like.
There are a few modules in this situation in fact.

**Describe alternatives you've considered**
Might be a place for me to learn how to do this.

**Additional context**
14 is the Master Branch still.  
I do need to also understand how to update this via Git Pull and also update my database at the same time.  I can do that bringing in new modules but I saw one install (not mine) go south updating a whole slew of modules out of OCA that had recent updates.  (Yes, that is a separate, albeit related, subject).

**Comment by pedrobaeza** [comment]
Thanks for highlighting it. It seems this people has made the adaptation to v14 in their fork, which is valid according the license, and not very hard, but didn't contribute back to OCA. You can encourage them to do it so. What seems not correct is that they have replaced the author in the manifest. I will write about it.

Anyway, it they pretended to be in the Odoo apps store in the version 14, that's not possible, as Odoo has a mechanism for not allowing it:

https://apps.odoo.com/apps/modules/15.0/event_sale_reservation/

**Comment by l-arnold** [comment]
Is interesting and not clear.

In order to bring some of the missing apps into OCA 14 branch what would be the process?  Perhaps I can help..

to the general issue here.... also, this is a strange listing.  It shows OCA and Tecnativa yet it is listed by Vertel and I don't see the OCA file it comes from.
I think it is a rename of event/sale/reservation but has been stripped, or I am not sure what.

https://apps.odoo.com/apps/modules/14.0/event_reservation/
also here:
https://github.com/vertelab/odoo-event/tree/14.0/event_reservation

**Comment by pedrobaeza** [comment]
Seeing the code, it seems only a bridge module with few code, but no clear which is the purpose of it. Maybe just a bridge for appearing in the Odoo Apss as the name is not reserved.
