### ISSUE TITLE
[8.0][BUG] event_registration_cancel_reason - You cannot cancel registrations from events of different types at once. 

### ISSUE THREAD

**Issue by rafaelbn** [OCA/event#35]
module: event_registration_cancel_reason
version: 8.0

**Steps to reproduce**
- Try to cancel a registration in an Event which doesn't have set "Type of Event"

**Current behavior**
- You cannot cancel registrations from events of different types at once. 

**Expected behavior**
- If there is a cancel reason for all Type of Events, then you must be able to cancel registrations of events which do not have any Type assigned.

@yajo @pedrobaeza

**Comment by rafaelbn** [comment]
Fixed https://github.com/OCA/event/pull/36

**Comment by yajo** [comment]
Well, fixed when it gets merged.
