### ISSUE TITLE
[NEW][website_event_hidden] Have online register event without including in website

### ISSUE THREAD

**Issue by rafaelbn** [OCA/event#60]
Hello,

I would like to propose a new need.

You would like to send a link for registering an Event you manage in Odoo without posting it in you webpage. Like Google Drive, Youtube: All who has the link can register to the event, but it is not public.

Thanks
Regards

cc @pedrobaeza @Yajo @Tecnativa

**Comment by sergio-teruel** [comment]
:+1 good idea .. and is not complex to implement

**Comment by yajo** [comment]
You'd have to use a token for that, and would have to workaround the sitemap to avoid indexations for it, right?

**Comment by pedrobaeza** [comment]
Well, in this case is simpler, as everyone having the link can access. It's difficult with current controller to figure out the link.

**Comment by yajo** [comment]
Actually it's quite easy: just event/5, event/6, event/7... Odoo slug automatic completion does the rest.

**Comment by pedrobaeza** [comment]
Oh, I didn't know about that shortcut. I thought it was needed the dates and so on. Then a token is indeed needed.

**Comment by rafaelbn** [comment]
I think we implemented this. Isn't it? Do you know where?

**Comment by rafaelbn** [comment]
Any case... too old. Closing!
