### ISSUE TITLE
Can not create contact

### ISSUE THREAD

**Issue by gokhanerdogdu** [OCA/event#90]
Hello,

In event settings, although create partner option is enabled, during event registration from website new partners are not created. All event registrations are related with Public User if the registrar is a non logged in user.

**Comment by pedrobaeza** [comment]
Module? Version? Steps to reproduce?

**Comment by gokhanerdogdu** [comment]
Sorry for missing information. 
Module is partner_event module and Odoo version is the latest V10 version.

First install partner_event module. Then create an event with the option "Create Partners in registration" checked. Then go to website without logged in user and register to the event with Name, email and phone. Registration is completed and the registration is seen in the backend. So far so good.

It is expected to have the partner automatically created since there is no partner with that email, but no partner is created. Also, the registration is related with Public user on the contact field. 

I see this as an issue since Partner_event module description is like follows;
**Configuration**
There is a new option in event form view, "Create Partners in registration". If this option is checked, when you add registrations to this event, partners will be created automatically with name, email and phone fields.

If partner already exists and user only fills email, name and phone fields will be filled with partner's data.

The event registration values email, name and phone will be changed if the related partner values are changed and the event end date hasn't passed yet.

**Comment by chienandalu** [comment]
@gokhanerdogdu That is the default behavior for `website_event`: it sets the contact to the user doing the website registration. So it's not a `partner_event` issue.

What you'd need is another module wich overrides `website_event` and use `partner_event` methods. You're very welcome to contribute :smile:
